#FROM docker location

#COPY jar to destination eg COPY springboot_skeleton_service/target/spring-boot-template-image_version.jar /app/springboot_skeleton_service.jar
#COPY sh file to destination eg COPY springboot_skeleton_service/docker/start.sh /app

#USER root
#RUN yum -y install openssl \
   # && yum clean all
   
#Event Proocessing Service for Health check
#EXPOSE 8090
#ENV PATH $PATH:/opt/jre/latest/bin
#USER 1001
#ENTRYPOINT["app/start.sh"]

